export const plannedArrayDb = [
    {
      title: "Basic Plan",
      description: "Ideal for small websites and personal blogs",
      numberOfComments: 5,
      numberOfUpvotes: 34,
      status: "Planned",
      category: "Personal",
      createdAt: new Date("2022-10-01"),
    },
    {
      title: "WordPress Hosting",
      description: "Optimized for WordPress websites with one-click installation",
      numberOfComments: 8,
      numberOfUpvotes: 50,
      status: "Planned",
      category: "Web Hosting",
      createdAt: new Date("2020-11-15"),
    },
    {
      title: "VPS Hosting",
      description: "Virtual Private Server hosting with dedicated resources",
      numberOfComments: 18,
      numberOfUpvotes: 78,
      status: "Planned",
      category: "Web Hosting",
      createdAt: new Date("2021-09-05"),
    },
    {
      title: "Email Hosting",
      description: "Professional email hosting with advanced features",
      numberOfComments: 3,
      numberOfUpvotes: 22,
      status: "Planned",
      category: "Email Hosting",
      createdAt: new Date("2019-12-20"),
    },
  ];
  
  export const inProgressArrayDb = [
    {
      title: "Business Plan",
      description: "Perfect for small businesses and e-commerce sites",
      numberOfComments: 10,
      numberOfUpvotes: 72,
      status: "In Progress",
      category: "Business",
      createdAt: new Date("2021-08-10"),
    },
    {
      title: "Enterprise Plan",
      description: "For large enterprises with high traffic and performance needs",
      numberOfComments: 15,
      numberOfUpvotes: 98,
      status: "In Progress",
      category: "Business",
      createdAt: new Date("2019-07-25"),
    },
    {
      title: "Reseller Hosting",
      description: "Host and manage multiple websites with your own control panel",
      numberOfComments: 12,
      numberOfUpvotes: 125,
      status: "In Progress",
      category: "Web Hosting",
      createdAt: new Date("2019-11-30"),
    },
  ];
  
  export const completeArrayDb = [
    {
      title: "Pro Plan",
      description: "Designed for growing businesses and multiple websites",
      numberOfComments: 35,
      numberOfUpvotes: 112,
      status: "Complete",
      category: "Business",
      createdAt: new Date("2021-05-15"),
    },
    {
      title: "Cloud Hosting",
      description: "Scalable cloud hosting for high availability and performance",
      numberOfComments: 12,
      numberOfUpvotes: 65,
      status: "Complete",
      category: "Web Hosting",
      createdAt: new Date("2020-06-28"),
    },
    {
      title: "Dedicated Servers",
      description: "Full dedicated server for ultimate control and performance",
      numberOfComments: 25,
      numberOfUpvotes: 102,
      status: "Complete",
      category: "Web Hosting",
      createdAt: new Date("2020-07-10"),
    },
  ];
